### ISSUE TITLE
Auto-Install.xml file location

### ISSUE THREAD

**Issue by Aamir010** [f4bien/docker-digital-factory#1]
Hello,

Can you please help me with actual path of auto-install.xml. I need to change certain values based on my requirement. so it would be helpful for reference existing xml file

**Comment by f4bien** [comment]
Hello Aamir,

You can clone the repo and edit [auto-install.xml](https://github.com/f4bien/docker-digital-factory/blob/master/7.1/scripts/auto-install.xml) or [6.6 one](https://github.com/f4bien/docker-digital-factory/blob/master/6.6/scripts/auto-install.xml). Then, you have to run with `docker run`.

Kind regards,

**Comment by Aamir010** [comment]
Yeah got it.

But is there any reference guide for which tag is point to what argument? 

Actually I am planning to have multi-tier approach, and wants mysql in different container/server, so where do I put mysql parameters on xml file ?

**Comment by f4bien** [comment]
I recommend you to install once with the installer on your PC (not the console mode) and then export your install (the last step, I think). And then integrate that generated file to your project.

If you plan to configure a cluster maybe you could use [docker-compose](https://docs.docker.com/compose/).

**Comment by Aamir010** [comment]
Gotcha !
Currently I have installed this through linux shell but not getting and conf file. Later on I will install this with windows GUI, and let you know, if I was block or not
